@echo off
cd /d "%~dp0"
echo Cleaning up port 5175...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr /R /C:":5175.*LISTENING"') do (
    echo Killing process %%a...
    taskkill /f /pid %%a >nul 2>&1
)
echo Starting the Sabbath School Attendance App (Vite Dev Server)...
start /b cmd /c "npm run dev"
echo Waiting for server to initialize...
timeout /t 3 /nobreak > nul
echo Opening the app in your browser...
start http://localhost:5175/attendance/
echo Done! Please keep this window open while using the app.
